baseURL: https://blog.ukonnra.com/
title: Ukonn Ra Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags
          weight: 10
        - name: Categories
          url: categories
          weight: 15
        - name: Series
          url: series
          weight: 20
        - name: Search
          url: search
          weight: 25
  zh:
    languageName: "简中"
    languageAltTitle: "简体中文"
    weight: 2
    menu:
      main:
        - name: 归档
          url: archives
          weight: 5
        - name: 标签
          url: tags
          weight: 10
        - name: 分类
          url: categories
          weight: 15
        - name: 系列
          url: series
          weight: 20
        - name: 搜索
          url: search
          weight: 25
    title: "Ukonn Ra 技术博客"
    homeInfoParams:
      Title: "Ukonn Ra 技术博客"
      Content: >
        这里是 Ukonn Ra 的技术博客。
        我在这里分享有趣且实用的技术&编程等内容。
    editPost:
      URL: "https://github.com/UkonnRa/ukonnra.github.io/tree/main/content"
      Text: "编辑"
      appendFilePath: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Ukonn Ra Blog for Tech & Programming"
  author: Ukonn Ra

  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: "Ukonn Ra Blog"
    Content: >
      This is Ukonn Ra's personal tech blog. 
      I am sharing interesting and useful tech & programming content here.

  socialIcons:
    - name: github
      url: "https://github.com/UkonnRa"

  editPost:
    URL: "https://github.com/UkonnRa/ukonnra.github.io/tree/main/content"
    Text: "Edit"
    appendFilePath: true

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
